#version: '3.8'


services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smarthome-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"   # Standard MQTT
      - "9001:9001"   # WebSockets
    volumes:
      - ./smart_home/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api-app
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  humidity-temperature-sensors-service:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: humidity-temperature-sensors-service-app
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network
  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:

networks:
  smarthome-network:
    driver: bridge
