# --- Persistence ---
# This ensures retained messages are saved to disk
persistence true
persistence_location /mosquitto/data/
autosave_interval 60

# --- Standard MQTT (TCP) ---
# Port 1883 for your Go Producers/Subscribers
listener 1883 0.0.0.0
allow_anonymous true

# --- MQTT over WebSockets ---
# Port 9001 for your Web Clients
listener 9001 0.0.0.0
protocol websockets

# Logging for easier debugging during development
log_dest stdout